export const INITIAL_GIFTS = [
  {
    id: "gift-001",
    category: "Pañales y cuidado",
    name: "Pañales RN",
    description: "1 paquete de pañales para recién nacido",
    total: 8,
    active: true,
    order: 1,
  },
  {
    id: "gift-002",
    category: "Pañales y cuidado",
    name: "Pañales talle P",
    description: "1 paquete de pañales talle P",
    total: 10,
    active: true,
    order: 2,
  },
  {
    id: "gift-003",
    category: "Pañales y cuidado",
    name: "Pañales talle M",
    description: "1 paquete de pañales talle M",
    total: 10,
    active: true,
    order: 3,
  },
  {
    id: "gift-004",
    category: "Pañales y cuidado",
    name: "Pañales talle G",
    description: "1 paquete de pañales talle G",
    total: 8,
    active: true,
    order: 4,
  },
  {
    id: "gift-005",
    category: "Pañales y cuidado",
    name: "Toallitas húmedas",
    description: "Pack de toallitas húmedas para bebé",
    total: 10,
    active: true,
    order: 5,
  },
  {
    id: "gift-006",
    category: "Pañales y cuidado",
    name: "Algodón o gasas",
    description: "Algodón o gasas suaves para higiene",
    total: 5,
    active: true,
    order: 6,
  },
  {
    id: "gift-007",
    category: "Pañales y cuidado",
    name: "Crema para pañal",
    description: "Crema protectora para la zona del pañal",
    total: 4,
    active: true,
    order: 7,
  },
  {
    id: "gift-008",
    category: "Baño e higiene",
    name: "Set de higiene",
    description: "Cepillo, peine, cortaúñas y accesorios",
    total: 2,
    active: true,
    order: 8,
  },
  {
    id: "gift-009",
    category: "Baño e higiene",
    name: "Shampoo y jabón para bebé",
    description: "Productos suaves para baño del bebé",
    total: 4,
    active: true,
    order: 9,
  },
  {
    id: "gift-010",
    category: "Baño e higiene",
    name: "Toalla con capucha",
    description: "Toalla suave con capucha para bebé",
    total: 4,
    active: true,
    order: 10,
  },
  {
    id: "gift-011",
    category: "Baño e higiene",
    name: "Bañera para bebé",
    description: "Bañera infantil",
    total: 1,
    active: true,
    order: 11,
  },
  {
    id: "gift-012",
    category: "Baño e higiene",
    name: "Termómetro de baño",
    description: "Termómetro para controlar la temperatura del agua",
    total: 1,
    active: true,
    order: 12,
  },
  {
    id: "gift-013",
    category: "Ropita",
    name: "Bodies 0 a 3 meses",
    description: "Bodies de algodón manga corta o larga",
    total: 6,
    active: true,
    order: 13,
  },
  {
    id: "gift-014",
    category: "Ropita",
    name: "Bodies 3 a 6 meses",
    description: "Bodies de algodón manga corta o larga",
    total: 6,
    active: true,
    order: 14,
  },
  {
    id: "gift-015",
    category: "Ropita",
    name: "Enteritos o pijamas 0 a 3 meses",
    description: "Enteritos cómodos para dormir",
    total: 5,
    active: true,
    order: 15,
  },
  {
    id: "gift-016",
    category: "Ropita",
    name: "Enteritos o pijamas 3 a 6 meses",
    description: "Enteritos cómodos para dormir",
    total: 5,
    active: true,
    order: 16,
  },
  {
    id: "gift-017",
    category: "Ropita",
    name: "Medias para bebé",
    description: "Pares de medias suaves",
    total: 5,
    active: true,
    order: 17,
  },
  {
    id: "gift-018",
    category: "Ropita",
    name: "Gorritos para bebé",
    description: "Gorritos suaves de algodón",
    total: 3,
    active: true,
    order: 18,
  },
  {
    id: "gift-019",
    category: "Ropita",
    name: "Mantas o muselinas",
    description: "Manta liviana o muselina para bebé",
    total: 5,
    active: true,
    order: 19,
  },
  {
    id: "gift-020",
    category: "Alimentación",
    name: "Baberos",
    description: "Baberos de tela o impermeables",
    total: 5,
    active: true,
    order: 20,
  },
  {
    id: "gift-021",
    category: "Alimentación",
    name: "Set de mamaderas",
    description: "Set de mamaderas para recién nacido",
    total: 2,
    active: true,
    order: 21,
  },
  {
    id: "gift-022",
    category: "Alimentación",
    name: "Chupetes",
    description: "Chupetes adecuados para recién nacido",
    total: 3,
    active: true,
    order: 22,
  },
  {
    id: "gift-023",
    category: "Alimentación",
    name: "Cepillo limpia mamaderas",
    description: "Cepillo para limpieza de mamaderas y tetinas",
    total: 1,
    active: true,
    order: 23,
  },
  {
    id: "gift-024",
    category: "Alimentación",
    name: "Babero de silicona",
    description: "Babero de silicona para cuando empiece a comer",
    total: 2,
    active: true,
    order: 24,
  },
  {
    id: "gift-025",
    category: "Dormir",
    name: "Sábanas para cuna",
    description: "Juego de sábanas ajustables para cuna",
    total: 3,
    active: true,
    order: 25,
  },
  {
    id: "gift-026",
    category: "Dormir",
    name: "Protector impermeable de colchón",
    description: "Protector lavable para colchón de cuna",
    total: 2,
    active: true,
    order: 26,
  },
  {
    id: "gift-027",
    category: "Dormir",
    name: "Luz de noche",
    description: "Luz cálida y suave para el cuarto del bebé",
    total: 1,
    active: true,
    order: 27,
  },
  {
    id: "gift-028",
    category: "Paseo y organización",
    name: "Mochila maternal",
    description: "Mochila para llevar las cosas del bebé",
    total: 1,
    active: true,
    order: 28,
  },
  {
    id: "gift-029",
    category: "Paseo y organización",
    name: "Cambiador portátil",
    description: "Cambiador plegable para salidas",
    total: 2,
    active: true,
    order: 29,
  },
  {
    id: "gift-030",
    category: "Paseo y organización",
    name: "Portabebé",
    description: "Portabebé ergonómico",
    total: 1,
    active: true,
    order: 30,
  },
  {
    id: "gift-031",
    category: "Juego y estimulación",
    name: "Manta de actividades",
    description: "Manta de actividades para bebé",
    total: 1,
    active: true,
    order: 31,
  },
  {
    id: "gift-032",
    category: "Juego y estimulación",
    name: "Sonajeros o mordillos",
    description: "Juguetes suaves para estimulación",
    total: 3,
    active: true,
    order: 32,
  },
  {
    id: "gift-033",
    category: "Juego y estimulación",
    name: "Libros de tela",
    description: "Libros blanditos para los primeros meses",
    total: 3,
    active: true,
    order: 33,
  },
  {
    id: "gift-034",
    category: "Juego y estimulación",
    name: "Móvil para cuna",
    description: "Móvil decorativo para los primeros meses",
    total: 1,
    active: true,
    order: 34,
  },
  {
    id: "gift-035",
    category: "Paseo y organización",
    name: "Organizador de pañales",
    description: "Organizador para pañales y productos de higiene",
    total: 1,
    active: true,
    order: 35,
  },
  {
    id: "gift-036",
    category: "Paseo y organización",
    name: "Canasto organizador",
    description: "Canasto para ropa o accesorios del bebé",
    total: 2,
    active: true,
    order: 36,
  },
  {
    id: "gift-037",
    category: "Paseo y organización",
    name: "Cochecito para bebé",
    description: "Cochecito práctico y cómodo para paseos con el bebé",
    total: 1,
    active: true,
    order: 37,
  },
  {
    id: "gift-038",
    category: "Paseo y organización",
    name: "Silla para auto (huevito)",
    description: "Silla de seguridad para trasladar al bebé en el auto",
    total: 1,
    active: true,
    order: 38,
  },
  {
    id: "gift-039",
    category: "Alimentación",
    name: "Sillita para comer",
    description: "Silla alta para acompañar la etapa de alimentación del bebé",
    total: 1,
    active: true,
    order: 39,
  },
  {
    id: "gift-040",
    category: "Juego y estimulación",
    name: "Gimnasio para bebé",
    description: "Gimnasio con arco, juguetes y actividades para estimular al bebé",
    total: 1,
    active: true,
    order: 40,
  },
  {
    id: "gift-041",
    category: "Paseo y organización",
    name: "Mecedora para bebé",
    description: "Mecedora o hamaca cómoda para momentos de descanso y juego supervisado",
    total: 1,
    active: true,
    order: 41,
  },
  {
    id: "gift-042",
    category: "Dormir",
    name: "Cuna colecho",
    description: "Cuna colecho para los primeros meses del bebé",
    total: 1,
    active: true,
    order: 42,
  },
  {
    id: "gift-043",
    category: "Dormir",
    name: "Monitor para bebé",
    description: "Monitor de audio o video para acompañar al bebé desde otra habitación",
    total: 1,
    active: true,
    order: 43,
  },
  {
    id: "gift-044",
    category: "Alimentación",
    name: "Esterilizador de mamaderas",
    description: "Esterilizador para mamaderas, tetinas y accesorios",
    total: 1,
    active: true,
    order: 44,
  },
  {
    id: "gift-045",
    category: "Alimentación",
    name: "Calienta mamaderas",
    description: "Calentador de mamaderas para facilitar la preparación de las tomas",
    total: 1,
    active: true,
    order: 45,
  },
  {
    id: "gift-046",
    category: "Alimentación",
    name: "Almohadón de lactancia",
    description: "Almohadón de apoyo para lactancia y alimentación del bebé",
    total: 1,
    active: true,
    order: 46,
  },
];

export function buildEmptySlots(total) {
  const slots = {};
  const count = Math.max(1, Number(total) || 1);

  for (let index = 1; index <= count; index += 1) {
    const slotId = `slot-${String(index).padStart(2, "0")}`;
    slots[slotId] = {
      claimedBy: "",
      reservationId: "",
    };
  }

  return slots;
}

export function buildGiftsRecord(gifts = INITIAL_GIFTS) {
  const record = {};

  gifts.forEach((gift) => {
    record[gift.id] = {
      category: gift.category,
      name: gift.name,
      description: gift.description,
      total: gift.total,
      active: gift.active,
      order: gift.order,
    };
  });

  return record;
}

export function buildSlotsRecord(gifts = INITIAL_GIFTS) {
  const record = {};

  gifts.forEach((gift) => {
    record[gift.id] = buildEmptySlots(gift.total);
  });

  return record;
}
